#pragma once
#define PIN_LORA_CS 5
#define PIN_LORA_RST 14
#define PIN_LORA_DIO0 26
#define PIN_STEP 16
#define PIN_DIR 17
#define PIN_ENABLE 4
#define PIN_ESTOP 32
#define PIN_LIMIT_TOP 33
#define PIN_LIMIT_BOTTOM 13
#define MAX_TRAVEL_STEPS 5000L
#define MOTOR_TIMEOUT_MS 15000UL
#define TELEMETRY_INTERVAL_MS 2000UL
#define MAX_PAYLOAD_BYTES 240
#define USE_SIMULATED_SENSORS 1
